// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using christiansoe;

namespace christiansoe.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211027153736_UpdatedTestObjectsV2")]
    partial class UpdatedTestObjectsV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("christiansoe.Data.models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 55.32056080268012,
                            Longitude = 15.186943327270084,
                            Name = "Store Tårn"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 55.322358296440449,
                            Longitude = 15.187498428676713,
                            Name = "Test2"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 55.320211820087565,
                            Longitude = 15.192855386557753,
                            Name = "Test3"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 55.320571989523117,
                            Longitude = 15.186922340149591,
                            Name = "Test4"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 55.321184404696957,
                            Longitude = 15.188906945432864,
                            Name = "Test5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
