// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using christiansoe;

namespace christiansoe.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211110082031_UpdatedDB03")]
    partial class UpdatedDB03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("christiansoe.Data.models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsChecked = false,
                            Latitude = 55.320729999999998,
                            Longitude = 15.186030000000001,
                            Name = "Færgeteminal"
                        },
                        new
                        {
                            Id = 2,
                            IsChecked = false,
                            Latitude = 55.320205000000001,
                            Longitude = 15.192849000000001,
                            Name = "Østerkær - Danmarks østligeste punkt"
                        },
                        new
                        {
                            Id = 3,
                            IsChecked = false,
                            Latitude = 55.322264877099769,
                            Longitude = 15.187511167143466,
                            Name = "Hestehytten"
                        },
                        new
                        {
                            Id = 4,
                            IsChecked = false,
                            Latitude = 55.321274614803706,
                            Longitude = 15.187012128055752,
                            Name = "Christians Ø Kirke"
                        },
                        new
                        {
                            Id = 5,
                            IsChecked = false,
                            Latitude = 55.320439,
                            Longitude = 15.186107,
                            Name = "Broen mellem Christiansø og Frederiksø"
                        },
                        new
                        {
                            Id = 6,
                            IsChecked = false,
                            Latitude = 55.32056080268012,
                            Longitude = 15.186943327270084,
                            Name = "Store Tårn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
